[package]
name = "ore-tls-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
x509-parser = "0.16"
x25519-dalek = "2"
hmac = "0.12"
sha2 = "0.10"


[[bin]]
name = "client"
path = "src/client/main.rs"

[[bin]]
name = "server"
path = "src/server/main.rs"
